### PR TITLE
Cdodge/restricted oauth2 applications

### PR DESCRIPTION
**Pull request by chrisndodge**

### CODE REVIEW

**Comment by chrisndodge** [comment]
@pdpinch here is the changeset that we discussed the other day. This is just a preview of the changes in my personal fork. We're going to set up a formal PR to upstream edx-platform soon. It'd be great if you could just do a quick eyeball. This PR shouldn't change any existing behavior for your application, but - if you'd be open to it - rather than having a "blacklist" of RestrictedApplications (as currently implemented), I'd prefer a list of whitelisted PriveledgedApplications. However that would require an intermediate "hop" in terms of rollout. We'd have to disable the feature (add a feature flag), deploy the new datamodel, "whitelist" your application, then enable the feature.

Make sense?

Thanks for any feedback.

**Comment by chrisndodge** [comment]
@chenriksson I'll be setting up a PR to our org's fork of edx-platform. Then we'll set up a PR upstream to edX's master. We can discuss next week.

**Comment by chrisndodge** [comment]
Closing so I can re-open against Microsoft's fork

**Comment by pdpinch** [comment]
Sorry I didn't get to this on Friday. Is the upstream PR open now?

**Comment by chrisndodge** [comment]
@pdpinch, first step is for me to merge into Microsoft's fork (https://github.com/Microsoft/edx-platform/pull/1). Then we open up a PR against upstream edX, as the OSS submission will be coming under Microsofts Enterprise Contributor Agreement

**Pull request closed without merging**
